name: Deployment

on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - run: echo "Deploying to DEV"

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: beta

    steps:
      - run: echo "Deploying to BETA"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - run: echo "Deploying to PRODUCTION"

    
      